# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('comment', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='culture_tourism.Base')),
                ('category', models.CharField(choices=[('wedding', 'Wedding'), ('holiday', 'Holiday'), ('clothes', 'Clothes'), ('game', 'Game'), ('symbol', 'Symbol'), ('song', 'Song'), ('fairytale', 'Fairytale'), ('maqol', 'Maqol'), ('donli', 'Donli ekinlar'), ('meva', 'Meva'), ('sabzavot', 'Sabzavot'), ('qazilma', 'Qazilma'), ('sanat', "San'at"), ('obida', 'Obida'), ('zamonaviy-bino', 'Zamonaviy bino')], default='holiday', max_length=50)),
                ('photo', models.ImageField(upload_to='gallery/')),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('culture_tourism.base',),
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='culture_tourism.Base')),
                ('lib_name', models.CharField(blank=True, max_length=255)),
                ('lib_photo', models.ImageField(blank=True, upload_to='library/')),
                ('lib_file', models.FileField(blank=True, upload_to='library/')),
                ('lib_description', models.TextField(blank=True)),
                ('lib_created', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('culture_tourism.base',),
        ),
        migrations.CreateModel(
            name='NationalInfo',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='culture_tourism.Base')),
                ('info_category', models.CharField(choices=[('wedding', 'Wedding'), ('holiday', 'Holiday'), ('clothes', 'Clothes'), ('game', 'Game'), ('symbol', 'Symbol'), ('song', 'Song'), ('fairytale', 'Fairytale'), ('maqol', 'Maqol'), ('donli', 'Donli ekinlar'), ('meva', 'Meva'), ('sabzavot', 'Sabzavot'), ('qazilma', 'Qazilma'), ('sanat', "San'at"), ('obida', 'Obida'), ('zamonaviy-bino', 'Zamonaviy bino')], default='holiday', max_length=50)),
                ('info_title', models.CharField(blank=True, max_length=255)),
                ('info_photo', models.ImageField(blank=True, upload_to='national/')),
                ('info_body', models.TextField()),
                ('info_author', models.CharField(blank=True, max_length=100)),
                ('info_created', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('culture_tourism.base',),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='culture_tourism.Base')),
                ('news_title', models.CharField(blank=True, db_index=True, max_length=200)),
                ('news_slug', models.SlugField(blank=True, max_length=200)),
                ('news_photo', models.ImageField(blank=True, upload_to='news/')),
                ('news_body', models.TextField()),
                ('news_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            bases=('culture_tourism.base',),
        ),
        migrations.CreateModel(
            name='OtherInfo',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='culture_tourism.Base')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone_1', models.CharField(blank=True, max_length=15)),
                ('phone_2', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
            ],
            bases=('culture_tourism.base',),
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='culture_tourism.Base')),
                ('promo_photo', models.ImageField(blank=True, upload_to='promo/')),
                ('promo_text', models.TextField(blank=True)),
            ],
            bases=('culture_tourism.base',),
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='culture_tourism.Base')),
                ('region_name', models.CharField(choices=[('toshkent', 'Toshkent'), ('andijon', 'Andijon'), ('fargona', "Farg'ona"), ('namangan', 'Namangan'), ('sirdaryo', 'Sirdaryo'), ('jizzax', 'Jizzaz'), ('samarqand', 'Samarqand'), ('qashqadaryo', 'Qashqadaryo'), ('surhondaryo', 'Surhondaryo'), ('buxoro', 'Buxoro'), ('navoiy', 'Navoiy'), ('xorazm', 'Xorazm'), ('qoraqalpogiston', "Qoraqalpog'iston")], default='toshkent', max_length=70)),
                ('region_photo', models.ImageField(blank=True, upload_to='regions/')),
                ('region_description', models.TextField()),
            ],
            bases=('culture_tourism.base',),
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='culture_tourism.Base')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, upload_to='writers/')),
                ('period', models.CharField(blank=True, choices=[('17', ' till XVII century'), ('17-20', 'XVII - XX centuries'), ('20', 'Since XX century')], default='20', max_length=50)),
                ('description', models.TextField()),
            ],
            bases=('culture_tourism.base',),
        ),
    ]
