# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('culture_tourism', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainArticle',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='culture_tourism.Base')),
                ('b_number', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('b_subtext', models.CharField(blank=True, max_length=200, null=True)),
                ('b_title', models.CharField(blank=True, max_length=200, null=True)),
                ('article_title', models.CharField(blank=True, max_length=255)),
                ('article_body', models.TextField()),
                ('article_photo', models.ImageField(upload_to='main_article/')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('culture_tourism.base',),
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='culture_tourism.Base')),
                ('title', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='slide/')),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('culture_tourism.base',),
        ),
    ]
