# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture_tourism', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinfo',
            name='menu_name',
            field=models.SlugField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='menyu',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Menu:'),
        ),
    ]
