# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture_tourism', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menyu',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Menu:'),
        ),
        migrations.AddField(
            model_name='menyu',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Menu:'),
        ),
        migrations.AddField(
            model_name='menyu',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Menu:'),
        ),
    ]
