# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culture_tourism', '0002_auto_20160718_0412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={},
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='active',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='created',
        ),
    ]
