# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 18:01
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('culture_tourism', '0003_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_title', models.CharField(blank=True, max_length=255)),
                ('info_photo', models.ImageField(blank=True, upload_to='national/')),
                ('info_body', ckeditor.fields.RichTextField()),
                ('info_author', models.CharField(blank=True, max_length=100)),
                ('info_created', models.DateTimeField(auto_now_add=True)),
                ('info_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='culture_tourism.Menu')),
                ('info_sub_menu', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenu', to='culture_tourism.SubMenu')),
            ],
        ),
        migrations.CreateModel(
            name='SubArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(blank=True, max_length=255, null=True)),
                ('article_body', ckeditor.fields.RichTextField()),
                ('article_photo', models.ImageField(blank=True, null=True, upload_to='main_article/')),
            ],
        ),
        migrations.RemoveField(
            model_name='nationalinfo',
            name='info_menu',
        ),
        migrations.RemoveField(
            model_name='nationalinfo',
            name='info_sub_menu',
        ),
        migrations.RemoveField(
            model_name='mainarticle',
            name='article_body1',
        ),
        migrations.RemoveField(
            model_name='mainarticle',
            name='article_body2',
        ),
        migrations.RemoveField(
            model_name='mainarticle',
            name='article_body3',
        ),
        migrations.RemoveField(
            model_name='mainarticle',
            name='article_photo1',
        ),
        migrations.RemoveField(
            model_name='mainarticle',
            name='article_photo2',
        ),
        migrations.RemoveField(
            model_name='mainarticle',
            name='article_photo3',
        ),
        migrations.RemoveField(
            model_name='mainarticle',
            name='article_title1',
        ),
        migrations.RemoveField(
            model_name='mainarticle',
            name='article_title2',
        ),
        migrations.RemoveField(
            model_name='mainarticle',
            name='article_title3',
        ),
        migrations.RemoveField(
            model_name='mainarticle',
            name='b_word1',
        ),
        migrations.RemoveField(
            model_name='mainarticle',
            name='b_word2',
        ),
        migrations.RemoveField(
            model_name='mainarticle',
            name='b_word3',
        ),
        migrations.AlterField(
            model_name='news',
            name='news_body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='relatedtotopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related', to='culture_tourism.GeneralInfo'),
        ),
        migrations.DeleteModel(
            name='NationalInfo',
        ),
        migrations.AddField(
            model_name='subarticle',
            name='mainArticle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subarticles', to='culture_tourism.MainArticle'),
        ),
    ]
