# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('culture_tourism', '0004_auto_20160622_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostVisited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region', to='culture_tourism.Regions')),
            ],
        ),
    ]
