# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture_tourism', '0005_auto_20160613_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('wedding-sovchi', 'Wedding-Sovchilik'), ('wedding-toyoldi', 'Wedding-Toy-oldi'), ('wedding-kelin-salom', 'Wedding-Kelin-salom'), ('wedding-beshik-toy', 'Wedding-Beshik-toy'), ('holiday', 'Holiday'), ('clothes', 'Clothes'), ('game', 'Game'), ('symbol', 'Symbol'), ('song', 'Song'), ('fairytale', 'Fairytale'), ('maqol', 'Maqol'), ('donli', 'Donli ekinlar'), ('meva', 'Meva'), ('sabzavot', 'Sabzavot'), ('qazilma', 'Qazilma'), ('sanat', "San'at"), ('obida', 'Obida'), ('zamonaviy-bino', 'Zamonaviy bino')], default='holiday', max_length=50),
        ),
        migrations.AlterField(
            model_name='nationalinfo',
            name='info_category',
            field=models.CharField(choices=[('wedding-sovchi', 'Wedding-Sovchilik'), ('wedding-toyoldi', 'Wedding-Toy-oldi'), ('wedding-kelin-salom', 'Wedding-Kelin-salom'), ('wedding-beshik-toy', 'Wedding-Beshik-toy'), ('holiday', 'Holiday'), ('clothes', 'Clothes'), ('game', 'Game'), ('symbol', 'Symbol'), ('song', 'Song'), ('fairytale', 'Fairytale'), ('maqol', 'Maqol'), ('donli', 'Donli ekinlar'), ('meva', 'Meva'), ('sabzavot', 'Sabzavot'), ('qazilma', 'Qazilma'), ('sanat', "San'at"), ('obida', 'Obida'), ('zamonaviy-bino', 'Zamonaviy bino')], default='holiday', max_length=50),
        ),
        migrations.AlterField(
            model_name='otherinfo',
            name='phone_1',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AlterField(
            model_name='otherinfo',
            name='phone_2',
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
