# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-29 04:22
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture_tourism', '0007_auto_20160623_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(blank=True, help_text='Name', max_length=150),
        ),
        migrations.AlterField(
            model_name='slide',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
