# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-29 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('culture_tourism', '0008_auto_20160629_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalinfo',
            old_name='info_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='generalinfo',
            old_name='info_body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='generalinfo',
            old_name='info_photo',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='generalinfo',
            old_name='info_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='subarticle',
            old_name='article_body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='subarticle',
            old_name='article_photo',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='subarticle',
            old_name='article_title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='subarticle',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mainarticle',
            name='b_tild',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
