# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-29 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture_tourism', '0009_auto_20160629_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainarticle',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
