# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-30 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture_tourism', '0010_mainarticle_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatedtotopic',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='generalinfo',
            name='body',
        ),
        migrations.RemoveField(
            model_name='generalinfo',
            name='info_created',
        ),
        migrations.RemoveField(
            model_name='generalinfo',
            name='info_slug',
        ),
        migrations.RemoveField(
            model_name='generalinfo',
            name='is_small_text',
        ),
        migrations.RemoveField(
            model_name='generalinfo',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='generalinfo',
            name='title',
        ),
        migrations.RemoveField(
            model_name='mainarticle',
            name='created',
        ),
        migrations.RemoveField(
            model_name='mainarticle',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='subarticle',
            name='mainArticle',
        ),
        migrations.AddField(
            model_name='generalinfo',
            name='subarticle',
            field=models.ManyToManyField(related_name='generalinfo', to='culture_tourism.SubArticle'),
        ),
        migrations.AddField(
            model_name='mainarticle',
            name='subarticle',
            field=models.ManyToManyField(related_name='mainarticle', to='culture_tourism.SubArticle'),
        ),
        migrations.DeleteModel(
            name='RelatedToTopic',
        ),
    ]
