# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-30 21:01
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('culture_tourism', '0011_auto_20160701_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherinfo',
            name='description',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
