# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture_tourism', '0012_otherinfo_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='news_slug',
        ),
        migrations.AddField(
            model_name='news',
            name='news_data',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
