# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culture_tourism', '0013_auto_20160703_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='submenu',
            options={'ordering': ('-created',)},
        ),
    ]
