# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 06:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('culture_tourism', '0014_auto_20160703_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=250, unique_for_date='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submenu',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=250, unique_for_date='created'),
            preserve_default=False,
        ),
    ]
