# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture_tourism', '0017_auto_20160705_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=250),
        ),
    ]
