# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 03:34
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture_tourism', '0018_news_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='mostvisited',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='mostvisited',
            name='photo',
            field=models.ImageField(null=True, upload_to='most-visited/'),
        ),
    ]
