# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture_tourism', '0019_auto_20160709_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='mostvisited',
            name='n_slug',
            field=models.SlugField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='mostvisited',
            name='r_slug',
            field=models.SlugField(blank=True, max_length=250),
        ),
    ]
