# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 03:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culture_tourism', '0020_auto_20160709_0851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mostvisited',
            old_name='description',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='mostvisited',
            old_name='name',
            new_name='title',
        ),
    ]
