# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('culture_tourism', '0021_auto_20160709_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mostvisited',
            name='n_slug',
            field=models.SlugField(blank=True, editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='mostvisited',
            name='r_slug',
            field=models.SlugField(blank=True, editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='mostvisited',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='most_visiteds', to='culture_tourism.Regions'),
        ),
    ]
