# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 00:43
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culture_tourism', '0023_auto_20160709_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
