# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 00:54
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('culture_tourism', '0025_auto_20160712_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_body',
            field=redactor.fields.RedactorField(verbose_name='Text'),
        ),
    ]
