# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 06:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culture_tourism', '0027_auto_20160712_1108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-news_created',)},
        ),
    ]
