# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 10:31
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('culture_tourism', '0031_auto_20160712_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mostvisited',
            name='body',
            field=redactor.fields.RedactorField(null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='mostvisited',
            name='body_en',
            field=redactor.fields.RedactorField(null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='mostvisited',
            name='body_ru',
            field=redactor.fields.RedactorField(null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='mostvisited',
            name='body_uz',
            field=redactor.fields.RedactorField(null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='description',
            field=redactor.fields.RedactorField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='description_en',
            field=redactor.fields.RedactorField(null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='description_ru',
            field=redactor.fields.RedactorField(null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='description_uz',
            field=redactor.fields.RedactorField(null=True, verbose_name='Text'),
        ),
    ]
