# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('culture_tourism', '0032_auto_20160712_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maqollar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=512)),
                ('body', redactor.fields.RedactorField(verbose_name='Text')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
